apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-frontend
  labels:
    name: campus-frontend-deploy
    app: campus-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: campus-frontend-pod
      app: campus-frontend-app
  template:
    metadata:
      name: campus-frontend-pod
      labels:
        name: campus-frontend-pod
        app: campus-frontend-app
    spec:
      containers:
        - name: campus-frontend-container
          image: "038298882203.dkr.ecr.sa-east-1.amazonaws.com/campus-container-repositorie:v1.0"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5