apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-campus-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      campus: frontend
  template:
    metadata:
      labels:
        campus: frontend
    spec:
      containers:
      - name: campus-frontend
        image: lvallejos/campus-frontend:v1.1
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: campus-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    campus: frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001