apiVersion: v1
kind: Service
metadata:
  name: campus-frontend-service
  labels:
    name: campus-frontend-deploy
    app: campus-frontend-app
spec:
  type: NodePort
  selector:
    app: campus-frontend-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30001