on: [push]
name: action
jobs:
  campus-frontend:
    name: Campus Integration
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@master
      - name: building and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
