on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - name: Cancel Previous Redundant Build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install Dependencies
        run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Lint Execution
        run: npm run lint

  build:
    needs: install
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Building App
        run: npm run build
