on:
  push:
    branches:
      - main

jobs:
  campus-integration:
    runs-on: ubuntu-latest
    steps:
      - name: installing dependencies
        run: npm ci

      - name: Searching Syntax Errors
        run: npm run lint
      
      - name: Building App
        run: npm run build